project 'Thwack.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thwack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thwack
  pod 'Alamofire', '4.5.0'
  pod 'SwiftyJSON', '3.1.4'
  pod 'Socket.IO-Client-Swift'

end
